---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - http-route.yaml
  - service.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: '2026.6'
  - name: ghcr.io/matter-js/matterjs-server
    newTag: '1.1'

configMapGenerator:
  - name: home-assistant-config
    literals:
      - TZ=America/Los_Angeles
