apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - http-route.yaml
  - service.yaml
images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: latest
    digest: sha256:ceb1202133a5a036e8b03e20a10eb113186cc2f871968323c6fc6c3fc4205716
configMapGenerator:
  - name: home-assistant-config
    literals:
      - TZ=America/Los_Angeles
